---  
- hosts: localhost
  gather_facts: false
  connection: local
  become: yes

  vars:
    packages:
      - apache2
      - mysql-server
      - mysql-common
      - mysql-client
    services:
      - apache2
      - mysql

  tasks:
    - name: Install our packages
      apt:
        name: "{{ packages }}"
        state: present
    - name: Confirm services are running
      service:
        name: "{{ item }}"
        state: started
      with_items: "{{ services }}"
    - name: Enable Apache2 modssl
      shell: a2enmod ssl
    - name: Enable Apache2 Default HTTPS site
      shell: a2ensite default-ssl
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
